module.exports = {
  domain: "http://onesharemedia.club/",
  ENGLISH: 0,
  defaultLanguage: 0,
  typeMovieText: "movie",
  typeSeriesText: "series",
  typeMovie: 1,
  typeSeries: 2,
  perPage: 12,
  maxYearDistance: 12,
  listQuality: ["4K", "HD", "SD", "LQ"],

  constant: { server_data: "http://onesharemedia.club/anime/",
              server_image: "http://onesharemedia.club/img-anime/",

              noFilter: "**",
              genre: "genre",
              genres: "genres",
              movie: "movie",
              movieId: "movieId",
              video: "video",
              videoId: "videoId",
              season: "season",
              seasonsId: "seasonsId",
              episode: "episode",
              episodesId: "episodesId",
              pageIndex: "pageIndex",
              pageSize: "pageSize",
              filter: "filter",
  },
}